# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/focal64"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "../../", "/ccsm"

  # This needs the vagrant-disksize plugin
  #  https://github.com/sprotheroe/vagrant-disksize
  config.disksize.size = '40GB'

  config.vm.provider "virtualbox" do |vb|
    # Needs to be quite beefy to build clang
    vb.memory = "4096"
  end

  # Enable provisioning with a shell script.
  config.vm.provision "shell", inline: <<-SHELL

    sudo fallocate -l 8000M /swapfile
    sudo chmod 600 /swapfile
    sudo mkswap /swapfile
    sudo swapon /swapfile
    sudo sh -c 'echo "/swapfile none swap defaults 0 0" >> /etc/fstab'

    sudo apt-get update
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y zlib1g-dev libtool python gcc cmake g++ git

    if [ ! -d llvm ]; then
        sudo -u vagrant /vagrant/buildit.sh /ccsm
    fi

  SHELL
end
