name: CI

on: push

jobs:
  clang-format-action:
    name: clang-format-action
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: clang-format-action
        uses: bright-tools/clang-format-action@master
        with:
          clangversion: 12
