name: CI

on:
  pull_request

jobs:
  clang-format-action:
    name: clang-format-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: clang-format-action
        uses: bright-tools/clang-format-action@master
